CREATE TABLE country
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(255),
    continent VARCHAR(255)
);

CREATE TABLE host
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255),
    surname    VARCHAR(255),
    country_id BIGINT REFERENCES country ON DELETE CASCADE
);

CREATE TABLE accommodation
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(255),
    category  VARCHAR(50),
    host_id   BIGINT REFERENCES host ON DELETE CASCADE,
    num_rooms INTEGER
);

CREATE TABLE app_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255),
    name                       VARCHAR(255),
    surname                    VARCHAR(255),
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE,
    role                       VARCHAR(50)

);

CREATE TABLE reservations_list
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created  TIMESTAMP,
    user_username VARCHAR(255) REFERENCES app_users ON DELETE CASCADE
);

CREATE TABLE reservations_list_reservations
(
    reservations_list_id BIGINT REFERENCES reservations_list ON DELETE CASCADE,
    reservations_id      BIGINT REFERENCES accommodation ON DELETE CASCADE,
    PRIMARY KEY (reservations_list_id, reservations_id)
);

CREATE INDEX idx_host_country ON host (country_id);
CREATE INDEX idx_accommodation_host ON accommodation (host_id);
CREATE INDEX idx_user_username ON app_users (username);